### ISSUE TITLE
Why " (styles.OLink === '' && ['', 'o']) " ?

### ISSUE THREAD

**Issue by xeno-sun** [mishk0/swiper#1]
What's the thinking and consecution behind this sentence?

**Comment by mishk0** [comment]
``` js
pre = (Array.prototype.slice
      .call(styles)
      .join('') 
      .match(/-(moz|webkit|ms)-/) || (styles.OLink === '' && ['', 'o'])
    )[1]
```

We are searching a known prefix type, settling on Opera if none is found, because only Opera (Presto) has a `-o-link`. Then you get:

``` js
pre = (['', 'o'])[1] // 'o' 
```

**Comment by xeno-sun** [comment]
Okay, i got the result, thanks.

But there is last question: I couldn't find any infomation about the property "OLink", what is it ?

**Comment by mishk0** [comment]
You can find it here http://www.opera.com/docs/specs/opera7/

**Comment by xeno-sun** [comment]
Thanks again.
